stages:
- stage: Test
  jobs:
  - template: ./devtools/azure-pipelines-linux.yml
  - template: ./devtools/azure-pipelines-macos.yml

- stage: Coverage
  condition: succeeded()
  jobs:
    - job:
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - bash: echo "##vso[task.prependpath]$CONDA/bin" 
          displayName: Add conda to path

        - bash: sudo install -d -m 0777 /usr/envs
          displayName: Fix conda permissions

        - bash: |
            conda config --set always_yes yes --set changeps1 no
            conda config --add channels conda-forge
            conda create -n test-environment python=3.7 --file requirements.txt
            source activate test-environment
          displayName: Create new conda environment

        - bash: |
            source activate test-environment
            pip install -e .
          displayName: Installing analysis
          
        - bash: |
            source activate test-environment
            python -m pytest -v  --cov analysis --cov-report xml:./coverage.xml
            codecov --file coverage.xml --token $(CODECOV_TOKEN)
          displayName: Running tests
  
